#!/usr/bin/env ruby
# config.rb -- universal build.ninja generator
# Usage: ruby config.rb [debug|release]

MODE = (ARGV[0] || "debug").freeze

# --- DSL state ---
$libs = []
$exes = []
$mode_cflags = {}

def lib(name, srcs:)
  $libs << { name: name, srcs: srcs }
end

def exe(name, srcs:, deps: [])
  $exes << { name: name, srcs: srcs, deps: deps }
end

def debug(cflags:)
  $mode_cflags["debug"] = cflags
end

def release(cflags:)
  $mode_cflags["release"] = cflags
end

# --- Load project config ---
load File.join(__dir__, "config.in.rb")

# --- Detect toolchain ---
CC = ENV["CC"] || "cc"
AR = ENV["AR"] || "ar"

BASE_CFLAGS = "-std=c23 -Wall -Wextra -Werror -pedantic"
EXTRA_CFLAGS = $mode_cflags.fetch(MODE, "")
CFLAGS = "#{BASE_CFLAGS} #{EXTRA_CFLAGS}".strip

BUILDDIR = "build/#{MODE}"

# --- Generate build.ninja ---
File.open("build.ninja", "w") do |f|
  f.puts "# Generated by config.rb (mode=#{MODE})"
  f.puts "builddir = #{BUILDDIR}"
  f.puts ""
  f.puts "rule cc"
  f.puts "  command = #{CC} #{CFLAGS} -MMD -MF $out.d -c $in -o $out"
  f.puts "  depfile = $out.d"
  f.puts "  description = CC $in"
  f.puts ""
  f.puts "rule ar"
  f.puts "  command = #{AR} rcs $out $in"
  f.puts "  description = AR $out"
  f.puts ""

  link_flags = EXTRA_CFLAGS.include?("sanitize") ? EXTRA_CFLAGS : ""
  f.puts "rule link"
  f.puts "  command = #{CC} #{link_flags} $in -o $out"
  f.puts "  description = LINK $out"
  f.puts ""

  lib_outputs = {}

  # Libraries
  $libs.each do |lib|
    objs = lib[:srcs].map do |src|
      obj = "#{BUILDDIR}/#{src.sub(/\.c$/, '.o')}"
      f.puts "build #{obj}: cc #{src}"
      obj
    end
    ar_out = "#{BUILDDIR}/lib#{lib[:name]}.a"
    f.puts "build #{ar_out}: ar #{objs.join(' ')}"
    f.puts ""
    lib_outputs[lib[:name]] = ar_out
  end

  emitted = {}

  # Executables
  $exes.each do |exe|
    objs = exe[:srcs].map do |src|
      obj = "#{BUILDDIR}/#{src.sub(/\.c$/, '.o')}"
      unless emitted[obj]
        f.puts "build #{obj}: cc #{src}"
        emitted[obj] = true
      end
      obj
    end
    dep_archives = exe[:deps].map { |d| lib_outputs[d] }.compact
    all_inputs = (objs + dep_archives).join(' ')
    out = "#{BUILDDIR}/#{exe[:name]}"
    f.puts "build #{out}: link #{all_inputs}"
    f.puts ""
  end

  # Default: build everything
  all = $exes.map { |e| "#{BUILDDIR}/#{e[:name]}" }
  f.puts "default #{all.join(' ')}"
end

puts "Generated build.ninja (mode=#{MODE}, cc=#{CC})"
