#!/usr/bin/env ruby
# config.rb -- universal build.ninja generator
# Usage: ruby config.rb [debug|release]

MODE = (ARGV[0] || "debug").freeze

# --- DSL state ---
$libs = []
$exes = []
$combined_libs = []
$amalgamates = []
$dist_headers = []
$mode_cflags = {}

def lib(name, srcs:)
  $libs << { name: name, srcs: srcs }
end

def exe(name, srcs:, deps: [])
  $exes << { name: name, srcs: srcs, deps: deps }
end

def combined_lib(name, deps:)
  $combined_libs << { name: name, deps: deps }
end

def amalgamate(input:, output:, include_dirs: [])
  $amalgamates << { input: input, output: output, include_dirs: include_dirs }
end

def dist_header(src, to:)
  $dist_headers << { src: src, to: to }
end

def debug(cflags:)
  $mode_cflags["debug"] = cflags
end

def release(cflags:)
  $mode_cflags["release"] = cflags
end

# --- Load project config ---
load File.join(__dir__, "config.in.rb")

# --- Detect toolchain ---
CC = ENV["CC"] || "cc"
AR = ENV["AR"] || "ar"
CLANG_FORMAT = RUBY_PLATFORM =~ /darwin/ ? "xcrun clang-format" : "clang-format"

BASE_CFLAGS = "-std=c23 -Wall -Wextra -Werror -pedantic"
EXTRA_CFLAGS = $mode_cflags.fetch(MODE, "")
CFLAGS = "#{BASE_CFLAGS} #{EXTRA_CFLAGS}".strip

BUILDDIR = "build/#{MODE}"

# --- Amalgamate tool URL ---
def amalgamate_url
  case RUBY_PLATFORM
  when /darwin/
    "https://github.com/rindeal/Amalgamate/releases/download/v0.99.0/amalgamate-v0.99.0-darwin-arm64.zip"
  when /mingw|mswin|cygwin/
    "https://github.com/rindeal/Amalgamate/releases/download/v0.99.0/amalgamate-v0.99.0-windows-amd64.zip"
  else
    "https://github.com/rindeal/Amalgamate/releases/download/v0.99.0/amalgamate-v0.99.0-linux-amd64.zip"
  end
end

# --- Generate build.ninja ---
File.open("build.ninja", "w") do |f|
  f.puts "# Generated by config.rb (mode=#{MODE})"
  f.puts "builddir = #{BUILDDIR}"
  f.puts ""
  f.puts "rule cc"
  f.puts "  command = #{CC} #{CFLAGS} -MMD -MF $out.d -c $in -o $out"
  f.puts "  depfile = $out.d"
  f.puts "  description = CC $in"
  f.puts ""
  f.puts "rule ar"
  f.puts "  command = #{AR} rcs $out $in"
  f.puts "  description = AR $out"
  f.puts ""

  link_flags = EXTRA_CFLAGS.include?("sanitize") ? EXTRA_CFLAGS : ""
  f.puts "rule link"
  f.puts "  command = #{CC} #{link_flags} $in -o $out"
  f.puts "  description = LINK $out"
  f.puts ""

  lib_outputs = {}
  lib_objs = {}

  # Libraries
  $libs.each do |lib|
    objs = lib[:srcs].map do |src|
      obj = "#{BUILDDIR}/#{src.sub(/\.c$/, '.o')}"
      f.puts "build #{obj}: cc #{src}"
      obj
    end
    ar_out = "#{BUILDDIR}/lib#{lib[:name]}.a"
    f.puts "build #{ar_out}: ar #{objs.join(' ')}"
    f.puts ""
    lib_outputs[lib[:name]] = ar_out
    lib_objs[lib[:name]] = objs
  end

  emitted = {}

  # Executables
  $exes.each do |exe|
    objs = exe[:srcs].map do |src|
      obj = "#{BUILDDIR}/#{src.sub(/\.c$/, '.o')}"
      unless emitted[obj]
        f.puts "build #{obj}: cc #{src}"
        emitted[obj] = true
      end
      obj
    end
    dep_archives = exe[:deps].map { |d| lib_outputs[d] }.compact
    all_inputs = (objs + dep_archives).join(' ')
    out = "#{BUILDDIR}/#{exe[:name]}"
    f.puts "build #{out}: link #{all_inputs}"
    f.puts ""
  end

  # Combined libraries
  $combined_libs.each do |cl|
    all_objs = cl[:deps].flat_map { |d| lib_objs[d] || [] }
    out = "out/lib#{cl[:name]}.a"
    f.puts "build #{out}: ar #{all_objs.join(' ')}"
    f.puts ""
  end

  # Amalgamate
  unless $amalgamates.empty?
    tool_bin = "build/tools/amalgamate"
    url = amalgamate_url

    f.puts "rule download_amalgamate"
    f.puts "  command = mkdir -p build/tools && curl -sL #{url} -o build/tools/amalgamate.zip && unzip -o build/tools/amalgamate.zip -d build/tools/ > /dev/null && mv build/tools/*/amalgamate #{tool_bin} && chmod +x #{tool_bin}"
    f.puts "  description = DOWNLOAD amalgamate"
    f.puts ""
    f.puts "build #{tool_bin}: download_amalgamate"
    f.puts ""

    f.puts "rule amalgamate"
    f.puts "  command = #{tool_bin} $flags $in $out"
    f.puts "  description = AMALGAMATE $out"
    f.puts ""

    $amalgamates.each do |am|
      flags = am[:include_dirs].map { |d| "-i #{d}" }.join(' ')
      # Collect all source files as implicit deps for rebuild
      src_files = Dir.glob(am[:include_dirs].map { |d| "#{d}/*.{c,h}" }).sort.join(' ')
      f.puts "build #{am[:output]}: amalgamate #{am[:input]} | #{tool_bin} #{src_files}"
      f.puts "  flags = #{flags}"
      f.puts ""
    end
  end

  # Dist headers
  unless $dist_headers.empty?
    f.puts "rule cp"
    f.puts "  command = cp $in $out"
    f.puts "  description = CP $out"
    f.puts ""
    $dist_headers.each do |dh|
      f.puts "build #{dh[:to]}: cp #{dh[:src]}"
    end
    f.puts ""
  end

  # Default: build everything
  all = $exes.map { |e| "#{BUILDDIR}/#{e[:name]}" }
  all += $combined_libs.map { |cl| "out/lib#{cl[:name]}.a" }
  all += $amalgamates.map { |am| am[:output] }
  all += $dist_headers.map { |dh| dh[:to] }
  f.puts "default #{all.join(' ')}"
  f.puts ""

  # Format
  all_srcs = ($libs.flat_map { |l| l[:srcs] } + $exes.flat_map { |e| e[:srcs] }).uniq
  all_hdrs = all_srcs.flat_map { |s| [s.sub(/\.c$/, '.h'), s.sub(/\.c$/, '_intern.h')] }.select { |h| File.exist?(h) }
  fmt_files = (all_srcs + all_hdrs).sort.uniq.join(' ')
  f.puts "rule format"
  f.puts "  command = #{CLANG_FORMAT} -i $in"
  f.puts "  description = FORMAT"
  f.puts ""
  f.puts "build format: format #{fmt_files}"
end

puts "Generated build.ninja (mode=#{MODE}, cc=#{CC})"
